export const lightTheme = {
  name: 'ripsv-light',
  colors: {
    background: '#eff1f5',
    foreground: '#4c4f69',
    cursor: '#dc8a78',
    selection: '#ccd0da',
    lineHighlight: '#e6e9ef',
    sidebar: '#dce0e8',
    statusBar: '#ccd0da',
    tabActive: '#eff1f5',
    tabInactive: '#e6e9ef',
    border: '#ccd0da',
    accent: '#1e66f5',
    error: '#d20f39',
    warning: '#fe640b',
    success: '#40a02b',
  },
  tokenColors: {
    keyword: '#8839ef',
    string: '#40a02b',
    number: '#fe640b',
    comment: '#9ca0b0',
    function: '#1e66f5',
    variable: '#4c4f69',
    type: '#df8e1d',
    operator: '#04a5e5',
  },
};
